// <auto-generated />
using System;
using KIsabelSampleLibrary.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KIsabelSampleLibrary.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201128213757_addkits")]
    partial class addkits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KIsabelSampleLibrary.Entity.DrumKit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot0")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot11")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot12")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot13")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot14")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot15")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot9")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DrumKits");
                });

            modelBuilder.Entity("KIsabelSampleLibrary.Entity.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SamplesFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("addedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("bpm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("favorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("filename")
                        .HasColumnType("TEXT");

                    b.Property<string>("genres")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isFilePresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("key")
                        .HasColumnType("TEXT");

                    b.Property<int>("lengthMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.Property<string>("tags")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("KIsabelSampleLibrary.Entity.SamplesFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BasePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SamplesFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
